workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemagic

    environment:
      # ...  

    scripts:
      - name: Update Bundle Identifier
        script: |
          #!/bin/sh
          new_bundle_id='com.felico.aviator.cafe'
          old_bundle_id=$(awk -F '=' '/PRODUCT_BUNDLE_IDENTIFIER/ {print $2; exit}' $(pwd)/ios/Runner.xcodeproj/project.pbxproj)
          old_bundle_id=${old_bundle_id:0:$((${#old_bundle_id} - 1))}
          sed -i '' "s/${old_bundle_id}/${new_bundle_id}/g" $(pwd)/ios/Runner.xcodeproj/project.pbxproj

      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        script: |
          firebase login:ci --interactive

      - name: Configure Firebase for iOS
        script: |
          firebase use --add
          # Choose your Firebase project from the list and associate it with your Codemagic app.

      - name: Build and Deploy iOS App
        script: |
          # Build your iOS app here
          # Deploy your app using Firebase here
          
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
        earliest_release_date: 2021-12-01T14:00:00+00:00 
        copyright: own
